In [344]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re

In [345]:
df = pd.read_csv(r"D:\CDAC\DBDA\Data Analytics\MS_Dhoni_ODI_record.csv")
df.head()

,score,runs_scored,balls_faced,strike_rate,fours,sixes,opposition,ground,date,odi_number
0,0,0,1,0,0,0,v Bangladesh,Chattogram,23/12/2004,ODI # 2199
1,12,12,11,109.09,2,0,v Bangladesh,Dhaka,26/12/2004,ODI # 2201
2,7*,7,2,350,0,1,v Bangladesh,Dhaka,27/12/2004,ODI # 2202
3,3,3,7,42.85,0,0,v Pakistan,Kochi,02/04/2005,ODI # 2235
4,148,148,123,120.32,15,4,v Pakistan,Visakhapatnam,05/04/2005,ODI # 2236

In [346]:
df.shape
#there are 350 records with 10 columns

(350, 10)

In [347]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   score        350 non-null    object
 1   runs_scored  350 non-null    object
 2   balls_faced  350 non-null    object
 3   strike_rate  350 non-null    object
 4   fours        350 non-null    object
 5   sixes        350 non-null    object
 6   opposition   350 non-null    object
 7   ground       350 non-null    object
 8   date         350 non-null    object
 9   odi_number   350 non-null    object
dtypes: object(10)
memory usage: 27.5+ KB

In [348]:
#Number of matches dhoni did not play
df[(df['score'] == 'DNB') | (df['score'] == 'TDNB')].shape[0]

53

Removing DNB and TDNB matches

In [349]:
df_no_dnb = df[(df['score'] != 'DNB') & (df['score'] != 'TDNB')].copy()
len(df_no_dnb)

297

Converting or Casting to required data types

1.odi_number column

In [350]:
#df_no_dnb['odi_number'] = df_no_dnb['odi_number'].astype('string')
#df_no_dnb['odi_number'] = df_no_dnb['odi_number'].replace('[^0-9]','',regex = True)
#df_no_dnb['odi_number']

In [351]:
df_no_dnb['odi_number'] = df_no_dnb['odi_number'].str.replace('[^0-9]','',regex = True).astype('int')
df_no_dnb['odi_number']

0      2199
1      2201
2      2202
3      2235
4      2236
       ...
344    4169
345    4175
346    4179
347    4182
349    4190
Name: odi_number, Length: 297, dtype: int64

In [352]:
df_no_dnb.isna().sum()

score          0
runs_scored    0
balls_faced    0
strike_rate    0
fours          0
sixes          0
opposition     0
ground         0
date           0
odi_number     0
dtype: int64

2.converting to int

In [353]:
cols = ['runs_scored','balls_faced','fours','sixes']
#df_no_dnb[cols] = df_no_dnb[cols].apply(lambda x: pd.to_numeric(x,errors = 'coerce'))
df_no_dnb[cols] = df_no_dnb[cols].astype('int')

3.converting date column to datetime object

In [354]:
df_no_dnb['date'] = pd.to_datetime(df_no_dnb['date'],format = '%d/%m/%Y')

4.converting strike rate to float

In [355]:
df_no_dnb['strike_rate'] = df_no_dnb['strike_rate'].astype('float')

5.deriving a new column from score where dhoni is not out

In [356]:
df_no_dnb['not_out'] = np.where(df_no_dnb['score'].str.contains('*',regex = False),True,False)

In [357]:
df_no_dnb.head()

,score,runs_scored,balls_faced,strike_rate,fours,sixes,opposition,ground,date,odi_number,not_out
0,0,0,1,0.00,0,0,v Bangladesh,Chattogram,2004-12-23,2199,False
1,12,12,11,109.09,2,0,v Bangladesh,Dhaka,2004-12-26,2201,False
2,7*,7,2,350.00,0,1,v Bangladesh,Dhaka,2004-12-27,2202,True
3,3,3,7,42.85,0,0,v Pakistan,Kochi,2005-04-02,2235,False
4,148,148,123,120.32,15,4,v Pakistan,Visakhapatnam,2005-04-05,2236,False

6.converting score column to int

In [358]:
df_no_dnb['score'] = df_no_dnb['score'].str.replace('[^0-9]','',regex = True).astype('int')
df_no_dnb['score']

0        0
1       12
2        7
3        3
4      148
      ...
344     28
345     56
346     42
347     35
349     50
Name: score, Length: 297, dtype: int64

7.removing v from start of opposition column

In [378]:
df_no_dnb['opposition'] = df_no_dnb['opposition'].str.replace('^[vV]*','',regex = True).str.strip()
df_no_dnb['opposition']

0       Bangladesh
1       Bangladesh
2       Bangladesh
3         Pakistan
4         Pakistan
          ...
344    Afghanistan
345    West Indies
346        England
347     Bangladesh
349    New Zealand
Name: opposition, Length: 297, dtype: object

In [379]:
df_no_dnb.info()

<class 'pandas.core.frame.DataFrame'>
Index: 297 entries, 0 to 349
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   score        297 non-null    int64
 1   runs_scored  297 non-null    int64
 2   balls_faced  297 non-null    int64
 3   strike_rate  297 non-null    float64
 4   fours        297 non-null    int64
 5   sixes        297 non-null    int64
 6   opposition   297 non-null    object
 7   ground       297 non-null    object
 8   date         297 non-null    datetime64[ns]
 9   odi_number   297 non-null    int64
 10  not_out      297 non-null    bool
dtypes: bool(1), datetime64[ns](1), float64(1), int64(6), object(2)
memory usage: 25.8+ KB

In [380]:
df_no_dnb.head()

,score,runs_scored,balls_faced,strike_rate,fours,sixes,opposition,ground,date,odi_number,not_out
0,0,0,1,0.00,0,0,Bangladesh,Chattogram,2004-12-23,2199,False
1,12,12,11,109.09,2,0,Bangladesh,Dhaka,2004-12-26,2201,False
2,7,7,2,350.00,0,1,Bangladesh,Dhaka,2004-12-27,2202,True
3,3,3,7,42.85,0,0,Pakistan,Kochi,2005-04-02,2235,False
4,148,148,123,120.32,15,4,Pakistan,Visakhapatnam,2005-04-05,2236,False

In [381]:
df_no_dnb.describe()

,score,runs_scored,balls_faced,strike_rate,fours,sixes,date,odi_number
count,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297,297.000000
mean,36.272727,36.272727,41.424242,87.939966,2.781145,0.771044,2011-06-02 13:39:23.636363520,3099.511785
min,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,2004-12-23 00:00:00,2199.000000
25%,13.000000,13.000000,16.000000,61.290000,1.000000,0.000000,2007-09-08 00:00:00,2620.000000
50%,31.000000,31.000000,35.000000,81.940000,2.000000,0.000000,2010-08-16 00:00:00,3032.000000
75%,51.000000,51.000000,61.000000,109.830000,4.000000,1.000000,2015-02-15 00:00:00,3602.000000
max,183.000000,183.000000,145.000000,400.000000,15.000000,10.000000,2019-07-09 00:00:00,4190.000000
std,29.890278,29.890278,30.438715,47.480095,2.815722,1.292430,NaN,585.174091

In [438]:
#finding how many times dhoni scored a golden duck
golden_duck = (df_no_dnb['score'] == 0).sum()
golden_duck
#len(golden_duck)

np.int64(10)

In [391]:
#top 2 score 
df_no_dnb.nlargest(2,'score')

,score,runs_scored,balls_faced,strike_rate,fours,sixes,opposition,ground,date,odi_number,not_out
21,183,183,145,126.20,15,10,Sri Lanka,Jaipur,2005-10-31,2290,True
4,148,148,123,120.32,15,4,Pakistan,Visakhapatnam,2005-04-05,2236,False

In [392]:
df_no_dnb['ground'].unique()

array(['Chattogram', 'Dhaka', 'Kochi', 'Visakhapatnam', 'Jamshedpur',
       'Ahmedabad', 'Kanpur', 'Delhi', 'Dambulla', 'Colombo (RPS)',
       'Bulawayo', 'Harare', 'Nagpur', 'Jaipur', 'Pune', 'Vadodara',
       'Hyderabad (Deccan)', 'Kolkata', 'Mumbai', 'Peshawar', 'Lahore',
       'Multan', 'Karachi', 'Faridabad', 'Margao', 'Abu Dhabi',
       'Kingston', 'Basseterre', 'Port of Spain', 'Kuala Lumpur',
       'Mohali', 'Durban', 'Cape Town', 'Port Elizabeth', 'Centurion',
       'Cuttack', 'Rajkot', 'Bengaluru', 'Chennai', 'Belfast',
       'Southampton', 'Bristol', 'Birmingham', 'Manchester', 'Leeds',
       'The Oval', "Lord's", 'Chandigarh', 'Guwahati', 'Gwalior',
       'Brisbane', 'Melbourne', 'Canberra', 'Adelaide', 'Sydney',
       'Indore', 'Napier', 'Wellington', 'Christchurch', 'Auckland',
       'Gros Islet', 'Johannesburg', 'Chester-le-Street', 'Cardiff',
       'Perth', 'Hambantota', 'Pallekele', 'Ranchi', 'Dharamsala',
       'Hamilton', 'North Sound', 'Dubai (DSC)', 'Mumbai (BS)',
       'Mount Maunganui'], dtype=object)

In [412]:
#dhoni's highest score against australia
#grouped = df_no_dnb.groupby('opposition')
#grouped.get_group('Australia')['score'].max()  #or
grouped = df_no_dnb.groupby('opposition')['score'].max()
grouped.get('Australia')

np.int64(139)

In [425]:
#dhoni's highest score against australia on which ground
aus_df = df_no_dnb[df_no_dnb['opposition'] == 'Australia']
highest_row = aus_df.loc[aus_df['score'].idxmax()]
highest_row['ground']
#or

'Mohali'

In [426]:
highest_row = aus_df.nlargest(1,'score').iloc[0]
highest_row['ground']

'Mohali'

In [433]:
#dhoni's records at ranchi stadium
ranchi_df = df[df['ground'] == 'Ranchi']
ranchi_df.sort_values(by = 'score')

,score,runs_scored,balls_faced,strike_rate,fours,sixes,opposition,ground,date,odi_number
216,10*,10,12,83.33,2,0,v England,Ranchi,19/01/2013,ODI # 3322
281,11,11,31,35.48,0,0,v New Zealand,Ranchi,26/10/2016,ODI # 3799
340,26,26,42,61.9,2,1,v Australia,Ranchi,08/03/2019,ODI # 4109
229,DNB,-,-,-,-,-,v Australia,Ranchi,23/10/2013,ODI # 3422

In [442]:
#what are total number of sixes and fours
fours = df_no_dnb['fours'].sum()
sixes = df_no_dnb['sixes'].sum()
fours,sixes

(np.int64(826), np.int64(229))

In [445]:
#number of times dhoni didnt get out
notout_count = (df_no_dnb['not_out'] == True).sum()
notout_count

np.int64(84)

In [448]:
#how many times dhoni scored half_century
half_century = (df_no_dnb['score'] >= 50 ).sum()
half_century

np.int64(83)

In [449]:
#how many times dhoni scored full century
full_century = (df_no_dnb['score'] >= 100 ).sum()
full_century

np.int64(10)

So, you can say that from 83 half centuries he was able to turn only 10 full centuries